<?php

namespace BG\QuoteBundle\Repository;

/**
 * BaseServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
