security:

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        BG\UserBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN: [ROLE_USER, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
          id: fos_user.user_provider.username

        in_memory:
            memory:
              users:
                user:  { password: user, roles: [ 'ROLE_USER' ] }
                admin: { password: admin, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main_login:
            pattern:   ^/login$
            logout_on_user_change: true
            anonymous: true

        main:
            provider: main
            pattern:   ^/
            anonymous: false
            logout_on_user_change: true
            form_login:
              login_path: fos_user_security_login
              check_path: fos_user_security_check
            logout:
              path:       fos_user_security_logout
              target:     fos_user_security_login
            remember_me:
              secret:     '%secret%'
