<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHtprrm1\appProdDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHtprrm1/appProdDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHtprrm1.legacy');

    return;
}

if (!\class_exists(appProdDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHtprrm1\appProdDebugProjectContainer::class, appProdDebugProjectContainer::class, false);
}

return new \ContainerHtprrm1\appProdDebugProjectContainer(array(
    'container.build_hash' => 'Htprrm1',
    'container.build_id' => 'ef379d19',
    'container.build_time' => 1516919525,
));
