<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'BGCoreBundle\DataFixtures\ORM\LoadQuote' shared service.

return $this->services['BGCoreBundle\DataFixtures\ORM\LoadQuote'] = new \BGCoreBundle\DataFixtures\ORM\LoadQuote();
