<?php

namespace BG\CoreBundle\Repository;

/**
 * AdvancementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvancementRepository extends \Doctrine\ORM\EntityRepository
{
}
