<?php

namespace BG\CoreBundle\Repository;

use BG\CoreBundle\Entity\BaseService;

/**
 * BaseServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
