<?php

namespace BG\CoreBundle\Repository;

use BG\CoreBundle\Entity\BaseService;

/**
 * BaseServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BaseServiceRepository extends \Doctrine\ORM\EntityRepository
{
  public function findBase()
  {
    return $this->_em->createQuery('SELECT u FROM BGCoreBundle:BaseService u WHERE u INSTANCE OF BGCoreBundle:BaseService')->getResult();
  }
}
