<?php

namespace BG\CoreBundle\Repository;

/**
 * PlanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlanRepository extends \Doctrine\ORM\EntityRepository
{
  public function exists(int $code, string $level, string $drawing) : bool
  {
    return $this->_em->getRepository('BGCoreBundle:Plan')->findBy(
      array(
        'code' => $code,
        'level' => $level,
        'drawing' => $drawing
      ))->count() > 0;
  }
}
