<?php

namespace BG\CoreBundle\Repository;

use BG\CoreBundle\Entity\Status;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllByStatus(array $status)
  {
    $query = $this->_em->createQuery('SELECT q FROM BGCoreBundle:Quote q, BGCoreBundle:Status s WHERE q.status = s.id AND s.message IN (:status)');
    $query->setParameter('status', $status);
    return $query->getResult();
  }

  public function changeStatus(int $id, string $status)
  {
    $quote = $this->_em->getRepository('BGCoreBundle:Quote')->find($id);
    switch ($status)
    {
      case 'awaiting': $quote->setStatus(new Status("warning", "En attente"));
        break;
      case 'ongoing': $quote->setStatus(new Status("primary", "En cours"));
        break;
      case 'finished': $quote->setStatus(new Status("success", "Terminé"));
        break;
      case 'cancelled': $quote->setStatus(new Status("danger", "Annulé"));
        break;
    }

    $this->_em->flush();
  }

  public function updateVat(float $vat)
  {
    $quotes = $this->findAllByStatus(array('En attente', 'En cours'));

    foreach($quotes as $quote)
      $quote->setVat($vat);

    $this->_em->flush();
  }
}
