<?php

namespace BG\CoreBundle\Repository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends \Doctrine\ORM\EntityRepository
{
  public function findMaxAdvancement(int $id)
  {
    $service = $this->_em->getRepository('BGCoreBundle:Service')->find($id);

    $states = $service->getStates();

    if($states->isEmpty())
      throw new \Exception("Advancement collection is null");

    $max = $states[0];

    foreach($states as $state)
        if($max->getDate() < $state->getDate())
            $max = $state;
    return $max;
  }
}
