<?php

namespace BG\CoreBundle\Repository;

/**
 * SimpleServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SimpleServiceRepository extends \Doctrine\ORM\EntityRepository
{
}
