<?php

namespace BG\CoreBundle\Repository;

use BG\CoreBundle\Entity\Service;

/**
 * SlipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SlipRepository extends \Doctrine\ORM\EntityRepository
{
}
