BG_CoreBundle_view:
    path:     /view/{id}
    defaults: { _controller: BGCoreBundle:Core:view }
    requirements:
        id:   \d+

BG_CoreBundle_generateslip:
    path:     /generateslip/{id}
    defaults: { _controller: BGCoreBundle:Core:generateSlip }
    requirements:
        id:   \d+

BG_CoreBundle_pickdate:
    path:     /pick/{id}
    defaults: { _controller: BGCoreBundle:Core:pickDate }
    requirements:
        id:   \d+

BG_CoreBundle_slips:
    path:     /slips/{id}
    defaults: { _controller: BGCoreBundle:Core:slips }
    requirements:
        id:   \d+

BG_CoreBundle_selectLabels:
    path:     /labels/{id}
    defaults: { _controller: BGCoreBundle:Core:selectLabels }
    requirements:
        id:   \d+

BG_CoreBundle_round:
    path:     /round/{id}/{value}
    defaults: { _controller: BGCoreBundle:Core:round }
    requirements:
        id:   \d+
        value:   \d+
    options:
        expose: true

BG_CoreBundle_slip:
    path:     /slip/{id}
    defaults: { _controller: BGCoreBundle:Core:slip }
    requirements:
        id:   \d+

BG_CoreBundle_validate:
      path:     /validate/{id}
      defaults: { _controller: BGCoreBundle:Core:validate }
      requirements:
          id:   \d+

BG_CoreBundle_invalidate:
      path:     /invalidate/{id}
      defaults: { _controller: BGCoreBundle:Core:invalidate }
      requirements:
          id:   \d+

BG_CoreBundle_generate:
    path:     /generate/{id}
    defaults: { _controller: BGCoreBundle:Core:generate }
    requirements:
        id:   \d+

BG_CoreBundle_setAdvancement:
    path:     /set/{id}
    defaults: { _controller: BGCoreBundle:Core:setAdvancement }
    requirements:
        id:   \d+

BG_CoreBundle_invoice:
    path:     /invoice/{id}
    defaults: { _controller: BGCoreBundle:Core:invoice }
    requirements:
        id:   \d+

BG_CoreBundle_invoice_prod:
    path:     /invoice/prod/{id}
    defaults: { _controller: BGCoreBundle:Core:invoiceProd }
    requirements:
        id:   \d+

BG_CoreBundle_invoice_service:
    path:     /invoice/service/{id}
    defaults: { _controller: BGCoreBundle:Core:invoiceService }
    requirements:
        id:   \d+

BG_CoreBundle_getcustomers:
    path:     /getcustomers
    defaults: { _controller: BGCoreBundle:Core:getCustomers }
    options:
        expose: true

BG_CoreBundle_customer:
    path:     /customer
    defaults: { _controller: BGCoreBundle:Core:customer }

BG_CoreBundle_customers:
    path:     /customers/{action}
    defaults: { _controller: BGCoreBundle:Core:customers, action: add }
    options:
        expose: true

BG_CoreBundle_invoices:
    path:     /invoices
    defaults: { _controller: BGCoreBundle:Core:invoices }

BG_CoreBundle_archivesinvoices:
    path:     /archivesinvoices
    defaults: { _controller: BGCoreBundle:Core:archivesInvoices }

BG_CoreBundle_newquote:
    path:     /newquote/{nbBuilding}
    defaults: { _controller: BGCoreBundle:Core:newQuote, nbBuilding: 1  }
    requirements:
        nbBuilding:   \d+

BG_CoreBundle_modifyquote:
    path:     /modifyquote/{id}
    defaults: { _controller: BGCoreBundle:Core:modifyQuote }
    requirements:
        id:   \d+

BG_CoreBundle_changebuildings:
    path:     /changebuildings/{id}/{bid}/{action}
    defaults: { _controller: BGCoreBundle:Core:changeBuildings }
    requirements:
        id:   \d+
        bid:   \d+
        action:   "add|remove"

BG_CoreBundle_archives:
    path:     /archives
    defaults: { _controller: BGCoreBundle:Core:archives }

BG_CoreBundle_postquote:
    path:     /postquote
    defaults: { _controller: BGCoreBundle:Core:postquote }

BG_CoreBundle_settings:
    path:     /settings
    defaults: { _controller: BGCoreBundle:Core:settings }

BG_CoreBundle_changestatus:
    path:     /changestatus/{id}/{status}
    defaults: { _controller: BGCoreBundle:Core:changeStatus }
    requirements:
        id:   \d+
        status: "awaiting|ongoing|finished|cancelled"

BG_CoreBundle_home:
    path:     /
    defaults: { _controller: BGCoreBundle:Core:home }
