<?php

namespace BG\BillBundle\Repository;

/**
 * ArchivedBillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArchivedBillRepository extends \Doctrine\ORM\EntityRepository
{
  public function findAllByStatus(array $status)
  {
    $query = $this->_em->createQuery('SELECT q FROM BGBillBundle:ArchivedBill q, BGQuoteBundle:Status s WHERE q.status = s.id AND s.message IN (:status)');
    $query->setParameter('status', $status);
    return $query->getResult();
  }
}
