<?php

namespace BG\BillBundle\Repository;

/**
 * BillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BillRepository extends \Doctrine\ORM\EntityRepository
{
  public function getFindAllByStatusQuery(array $status)
  {
    $query = $this->_em->createQuery('SELECT q FROM BGBillBundle:Bill q JOIN BGQuoteBundle:Status s WHERE q.status = s.id AND s.message IN (:status)');
    $query->setParameter('status', $status);
    return $query;
  }
}
