<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHdevc1e\appDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHdevc1e/appDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerHdevc1e.legacy');

    return;
}

if (!\class_exists(appDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerHdevc1e\appDevDebugProjectContainer::class, appDevDebugProjectContainer::class, false);
}

return new \ContainerHdevc1e\appDevDebugProjectContainer(array(
    'container.build_hash' => 'Hdevc1e',
    'container.build_id' => '94bf6942',
    'container.build_time' => 1517092408,
));
